In [3]:
%logstop

In [4]:
%logstart

Activating auto-logging. Current session state plus future input saved.
Filename       : ipython_log.py
Mode           : rotate
Output logging : False
Raw input log  : False
Timestamping   : False
State          : active


In [6]:
!date

Tue Dec 19 15:59:01 CST 2017


In [7]:
!ls

data_python  ipython_log.py	  rabbit_mq
Init	     ipython_log.py.001~  Untitled.ipynb


In [8]:
date=!date

In [9]:
date

['Tue Dec 19 15:59:57 CST 2017']

In [10]:
a=2+2

In [11]:
a

4

In [12]:
%hist

%logstart
%logstart
%logstop
%logstart
!data
!date
!ls
date=!date
date
a=2+2
a
%hist


In [14]:
%hist -g a = 2

  14: %hist -g a = 2


In [16]:
%hist -g a = 2

  14: %hist -g a = 2
  15: %hist -g a = 2
  16: %hist -g a = 2


In [18]:
import numpy as np
a = np.arange(5)

In [19]:
a.dtype

dtype('int64')

In [20]:
a.shape

(5,)

In [22]:
m = np.array([np.arange(2), np.arange(2)])

In [23]:
m

array([[0, 1],
       [0, 1]])

In [24]:
m.shape

(2, 2)

In [25]:
ab=np.array([1,2,3], [4,5,6])

TypeError: data type not understood

In [26]:
ab=np.array([[1,2,3],[4,5]])

In [27]:
ab.shape

(2,)

In [28]:
ab.shape[0]

2

In [30]:
ab

array([[1, 2, 3], [4, 5]], dtype=object)

In [31]:
ab[0,0]

IndexError: too many indices for array

In [33]:
a

array([0, 1, 2, 3, 4])

In [34]:
a[0]

0

In [35]:
m[0]

array([0, 1])

In [36]:
ab[0]

[1, 2, 3]

In [37]:
ab[0,0]

IndexError: too many indices for array

In [ ]:
a